"""Report generation tools.

Produces structured markdown reports that summarise the calculation
pipeline, results, and scientific interpretation.  The report is
generated by a dedicated CrewAI agent (``report_writer``) that uses
an LLM to produce human-readable, publication-quality output.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Union

from ..utils.crewai_compat import tool


REPORT_TEMPLATE = """# {title}

> **Generated:** {date}
> **Language:** {language}
> **Pipeline:** {pipeline_summary}

---

## 1. 计算目标 / Objective

{objective}

---

## 2. 模型构建 / Model Construction

{model_construction}

---

## 3. 结构优化 / Structure Optimization

{optimization}

### 3.1 MLIP 预优化
{mlip_section}

### 3.2 DFT 精优化
{dft_section}

---

## 4. 能量与电子结构 / Energy & Electronic Structure

{energy_section}

### 4.1 DOS / PDOS 分析
{dos_section}

### 4.2 d-band Center
{dband_section}

---

## 5. 吸附能 / Adsorption Energy

{adsorption_section}

---

## 6. 自由能台阶图 / Free Energy Diagram

{volcano_section}

---

## 7. 结论与讨论 / Discussion

{discussion}

---

## 8. 计算参数 / Computational Details

{computational_details}

---

*Report generated automatically by slisaDFT Agent.*
"""


@tool
def generate_report_tool(data: str, output: str = "report.md",
                          language: str = "zh", title: str = "DFT 计算报告") -> str:
    """Generate a structured DFT calculation report.

    The tool collects all calculation results (provided as a JSON string)
    and assembles them into a formatted markdown report.  Sections that
    are empty are omitted.

    The report is written out to the specified file path.

    Args:
        data: JSON string containing all calculation results. Expected keys:
              objective, model_construction, optimization, mlip_section,
              dft_section, energy_section, dos_section, dband_section,
              adsorption_section, volcano_section, discussion,
              computational_details.
        output: output markdown file path.
        language: report language ('zh' for Chinese, 'en' for English).

    Returns:
        Path to the generated report file.
    """
    try:
        fields = json.loads(data)
    except (json.JSONDecodeError, TypeError) as exc:
        return f"Error: invalid JSON data ({exc})"

    fields["title"] = title
    fields["date"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    fields["language"] = language
    fields["pipeline_summary"] = fields.get("pipeline_summary", "DFT workflow")

    report = REPORT_TEMPLATE.format(**fields)

    out_path = Path(output)
    out_path.write_text(report, encoding="utf-8")
    return str(out_path.resolve())


@tool
def collect_results_tool(section_name: str, content: str) -> str:
    """Accumulate a section of the final report.

    This tool is called by the report agent to store each section's
    content.  It returns a confirmation message.

    Args:
        section_name: one of the report section keys.
        content: markdown-formatted content for that section.

    Returns:
        JSON confirmation.
    """
    # The actual accumulation is handled by the agent's state.
    return json.dumps({"section": section_name, "stored": True, "length": len(content)})


@tool
def finalize_report_tool(data: str, output: str = "report.md",
                          language: str = "zh") -> str:
    """Final step: write the completed report to disk.

    Args:
        data: JSON string of all report sections.
        output: output file path.
        language: 'zh' or 'en'.

    Returns:
        Path to the report file.
    """
    import json as _json
    fields = _json.loads(data) if isinstance(data, str) else data
    return generate_report_tool(_json.dumps(fields), output, language)