"""计算引擎抽象层（real / mock 双模式）。

通过环境变量 ``SLISADFT_ENGINE_MODE`` 切换：

* ``real``（默认）—— 调用真实引擎（VASP / CP2K / ABACUS / MACE / DPA-4），
  要求相应环境已按 ``docs/DEPLOYMENT.md`` 配置。
* ``mock`` —— 确定性 Mock 后端（ASE EMT / Lennard-Jones），在没有任何
  DFT 引擎的机器上端到端跑通流水线，用于演示、开发与 CI 测试。

Rule Zero 约束：mock 产物是合成数据。所有 mock 输出强制携带
``SYNTHETIC`` 标记，结果 JSON 中 ``engine_mode="mock"``、``synthetic=True``；
任何报告引用 mock 数据时必须如实声明，绝不可作为科研结论使用。
"""

from __future__ import annotations

import os

ENGINE_MODE_ENV = "SLISADFT_ENGINE_MODE"

SYNTHETIC_MARK = (
    "SYNTHETIC-DATA: generated by slisadft mock engine (EMT/LJ), "
    "NOT real DFT output. For demo/testing only — do not use as research data."
)


def engine_mode() -> str:
    """Return the configured engine mode: ``real`` or ``mock``."""
    mode = (os.environ.get(ENGINE_MODE_ENV) or "real").strip().lower()
    return mode if mode in ("real", "mock") else "real"


def is_mock() -> bool:
    """True when the mock engine backend should be used."""
    return engine_mode() == "mock"


def synthetic_result(payload: dict) -> dict:
    """Stamp a result dict with the mandatory SYNTHETIC markers (Rule Zero)."""
    payload = dict(payload or {})
    payload["engine_mode"] = "mock"
    payload["synthetic"] = True
    payload["synthetic_notice"] = SYNTHETIC_MARK
    return payload
